### ISSUE TITLE
Provide an option that enforces the documented syntax for Closure Compiler type expressions

### ISSUE THREAD

**Issue by pigulla** [hegemonic/catharsis#37]
Unless the `jsdoc` option is set, the following code should throw an exception because the type expression `null|function` is invalid (type unions must be within parentheses):

``` js
var catharsis = require('catharsis');

catharsis.parse('null|function()');
```

As I understand it, this behaviour was introduced in #8.

**Comment by hegemonic** [comment]
Closing this due to lack of interest.
