### ISSUE TITLE
Support intersection types.

### ISSUE THREAD

**Issue by joelday** [hegemonic/catharsis#49]
Same syntax as type unions, but with `&` instead of `|`.

https://flowtype.org/docs/union-intersection-types.html
https://www.typescriptlang.org/docs/handbook/advanced-types.html

Prerequisite for https://github.com/jsdoc3/jsdoc/issues/1285
Related to https://github.com/eslint/doctrine/issues/183

Thanks!

**Comment by hegemonic** [comment]
Sorry, but Catharsis only supports [Closure Compiler type expressions](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System), not Flow or TypeScript type expressions. This is unlikely to change anytime soon.
