### ISSUE TITLE
0.8.10 has breaking changes for node =< 8 and breaks jsdoc install, new version number requested

### ISSUE THREAD

**Issue by derekbar90** [hegemonic/catharsis#55]
The update 2 days ago causes build issues with servers running node lower than 8 due to dependency issues of Catharsis. 

Due to this module being a dependency of jsdoc and jsdoc having a ref of ~0.8.9, the install causes breaking builds when checking the node env. 

By changing the version number it will ensure backwards compat with modules linking via semver versioning schemes 

I recommend viewing this for reference: 

https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1

**Comment by hegemonic** [comment]
From the [semver 2.0.0 spec](https://semver.org/spec/v2.0.0.html):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
